dependencies:
  - dailyerosion
  - gdal
  - httpx
  - pandas
  # database
  - postgresql
  - psycopg
  - pydantic
  - pygrib
  # DISCIPLINE DARYL
  - pyiem >=1.25.0
  - pytest
  - pytest-cov
  - rasterio
  - reportlab
  - seaborn
  # For testing
  - werkzeug
  # Excel Export
  - xlsxwriter
